name: Pipeline Back

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop

jobs:
  check-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Run static analisys
        run: docker-compose run api pycodestyle --statistics .
      - name: Migrations
        run: docker-compose run api python3 manage.py migrate
      - name: Tests
        run: docker-compose run api python3 manage.py test

deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to heroku  
        uses: actions/checkout@v2
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_API }}
          dockerfile_directory: ./api/
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
